# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4094136a24c31557fcdfd79379f463d47e2770d63666cdf67e61f2d3d13e2be3287a7350c479d70715c80f75a7cdb13a957632d69bd26f96cbfd1e0d67eb6fe7

test:
  secret_key_base: 676937c733a2c445d699458fe3356bfd9f07fd94add43afe5aec94af6f2911e88c483f18548ec78d417ab3efc7d30ee746beb324fce940c505f048b3dc29cc7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
